#!/bin/bash

NAME="SpiralLinux_Budgie_12.231120"

###########################################################

while getopts "di" option; do
   case $option in
      d) # HDD image
            cp ./auto/hdd ./auto/config
            cp firmwarelists.sh /usr/share/live/build/functions/firmwarelists.sh ## Patched version for https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1018873
            if [ ! -f /root/live-build_memtest_patch_applied ]
			then
				patch -f -d/ -p0 < live-build_memtest.patch ## Many thanks for this patch from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1025795#10
            	touch /root/live-build_memtest_patch_applied
			fi
            lb clean
            lb config
            lb build;;
      i) # ISO image
            cp ./auto/iso ./auto/config
            cp firmwarelists.sh /usr/share/live/build/functions/firmwarelists.sh ## Patched version for https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1018873
            if [ ! -f /root/live-build_memtest_patch_applied ]
			then
				patch -f -d/ -p0 < live-build_memtest.patch ## Many thanks for this patch from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1025795#10
            	touch /root/live-build_memtest_patch_applied
			fi
            lb clean
            lb config
            lb build

     \?) # Invalid option
         echo "Error: Invalid option"
         exit;;
   esac
done
